reservasalas/reservas/forms.py
from wsgiref.validate import validator
from xmlrpc.client import boolean
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, DateField, TimeField, TextAreaField, BooleanField
from wtforms.validators import DataRequired, InputRequired, Length, Optional, NumberRange

class ReservaForm(FlaskForm):
    sala = SelectField(u'Sala', coerce=int, validators=[DataRequired(), NumberRange(min=0, message="Selecione uma sala para fazer reserva")]) #coerce faz com que o select retorne um valor especifico ao selecionar um item, no caso quero que ele retorne o id da sala escolhida
    observacoes = TextAreaField('Observações', validators=[Length(max=120)])
    data = DateField('Data', validators=[InputRequired()])
    hora_inicio = TimeField('Início', validators=[DataRequired()], format='%H:%M')
    hora_fim = TimeField('Fim', validators=[DataRequired()], format='%H:%M')
    repetir = BooleanField('Repetir toda semana', default=False)
    fim_repeticao = DateField('Repetir até', validators=[Optional()])
    submit = SubmitField('Reservar')

reservasalas/main/routes.py
from datetime import datetime
from flask import render_template, request, Blueprint
from reservasalas.models.models import Reservas, Sala
from reservasalas.utils.utility_functions import primeira_sala

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
	salas_query = Sala.query.order_by(Sala.id)
	page = request.args.get('page', 1, type=int) #parâmetro de consulta de páginas. Sem ele na próxima linha, apenas seria mostrada uma única página
	salas = salas_query.paginate(page=page, per_page=2) #fazendo com que não sejam mostradas todas as salas de uma única vez. Nesse caso serão mostrados apenas 5 posts
	reservas = Reservas.query.order_by()
	events_reservas = Reservas.query.order_by()
	return render_template('home.html', salas=salas, reservas=reservas, date=datetime.today(), events=events_reservas, primeira_sala=primeira_sala())

@main.route("/about")
def about():
	salas_query = Sala.query.order_by(Sala.sala)
	return render_template('about.html', title='About', primeira_sala=primeira_sala())

@main.route("/home_calendar/<int:sala_id>")
def home_calendar(sala_id):
	salas_query = Sala.query.order_by(Sala.sala)
	page = request.args.get('page', 1, type=int) #parâmetro de consulta de páginas. Sem ele na próxima linha, apenas seria mostrada uma única página
	salas = salas_query.paginate(page=page, per_page=2) #fazendo com que não sejam mostradas todas as salas de uma única vez. Nesse caso serão mostrados apenas 5 posts
	reservas = Reservas.query.order_by()
	if sala_id:
		sala = Sala.query.get_or_404(sala_id)
		reservasCalendar = Reservas.query.filter(Reservas.sala_id==sala.id)
	return render_template('home.html', salas=salas, reservas=reservas, date=datetime.today(), events=reservasCalendar, primeira_sala=primeira_sala())

"""@main.context_processor
def layout():
	form = SearchForm()
	return dict(form=form)

@main.route("/search", methods=["POST"])
def search():
	form = SearchForm()
	searched = form.searched.data
	if form.validate_on_submit():
		return render_template("search.html", form=form, searched=searched)"""

reservasalas/reservas/routes.py
from crypt import methods
from datetime import datetime, timedelta
from flask import (render_template, url_for, flash,
					redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from reservasalas import db
from reservasalas.models.models import Reservas, Sala
from reservasalas.reservas.forms import ReservaForm
from reservasalas.reservas.utils import verificaConflitoDataReservas
from flask import Blueprint
#from collections import namedtuple
from sqlalchemy import and_
from wtforms.validators import InputRequired
from reservasalas.utils.permissoes import verifica_permissao
from reservasalas.utils.utility_functions import primeira_sala

reservas = Blueprint('reservas', __name__)

@reservas.route("/reservas/nova_reserva/<int:sala_id>", methods=['GET', 'POST'])
@login_required
@verifica_permissao('cadastrar_reserva')
def nova_reserva(sala_id):
	form = ReservaForm()

	#trazendo as salas do banco de dados para o select de sala
	salas = Sala.query.order_by(Sala.sala)
	lista_salas = [(i.id, i.sala) for i in salas]
	form.sala.choices=lista_salas

	if form.repetir.data == True:
		form.fim_repeticao.validators=[InputRequired()]

	events_reservas = Reservas.query.filter(Reservas.sala_id==int(sala_id))

	if form.validate_on_submit():
		datetime_inicio = datetime.combine(form.data.data,form.hora_inicio.data)
		datetime_fim = datetime.combine(form.data.data,form.hora_fim.data)

		#trazendo a lista de reservas para verificar se há algum overlaping na hora de cadastrar reservas
		lista_reservas = Reservas.query.filter(and_(Reservas.fim>datetime.today(), Reservas.sala_id==form.sala.data))
		lista_horarios_reservas = [[inicio.inicio for inicio in lista_reservas], [fim.fim for fim in lista_reservas]]
		
		if form.hora_inicio.data>=form.hora_fim.data:
			flash('O horário final não pode ser menor ou igual ao horário inicial!')
		elif verificaConflitoDataReservas(lista_horarios_reservas, datetime_inicio, datetime_fim) == True: #verificando se há overlaping de reserva
			flash('Já existe uma reserva para esta sala neste horário!', 'warning')
		else :
			if form.repetir.data == True:
				date_fim_repeticao = form.fim_repeticao.data
				repeticoes = ((date_fim_repeticao-form.data.data).days)/7
				for i in range(0,int(repeticoes)):
					reserva = Reservas(sala_id=form.sala.data, observacoes=form.observacoes.data, reservante=current_user.username,
					inicio=datetime_inicio+timedelta(days=i * 7), fim=datetime_fim+timedelta(days=i*7), data_creacao=datetime.today(),
					sala_nome = Sala.query.get(form.sala.data).sala, author = current_user)
					db.session.add(reserva)
					db.session.commit()
				flash('Reservas cadastradas!', 'success')
			else:
				reserva = Reservas(sala_id=form.sala.data, observacoes=form.observacoes.data, reservante=current_user.username,
				inicio=datetime_inicio, fim=datetime_fim, data_creacao=datetime.today(), sala_nome=Sala.query.get(form.sala.data).sala, author = current_user)
				db.session.add(reserva)
				db.session.commit()
				flash('Reserva cadastrada!', 'success')
			return redirect(url_for('reservas.ver_reservas'))
	form.sala(autocomplete="on")

	return render_template('criar_reserva.html', title='Nova Sala', form = form, legend="Criar reserva", events=events_reservas, primeira_sala=primeira_sala())


@reservas.route("/reservas/<int:reserva_id>")
def reserva(reserva_id):
	reserva = Reservas.query.get_or_404(reserva_id)
	sala = Sala.query.get_or_404(reserva.sala_id)
	return render_template('reserva.html', reserva=reserva, sala=sala, primeira_sala=primeira_sala())

@reservas.route("/reservas/<int:reserva_id>/update", methods=['GET', 'POST'])
@login_required
@verifica_permissao('atualizar_reserva')
def update_reserva(reserva_id):
	reserva = Reservas.query.get_or_404(reserva_id)
	if reserva.author != current_user:
		abort(403)
	form = ReservaForm()
	salas = Sala.query.order_by(Sala.sala)
	lista_salas = [(i.id, i.sala) for i in salas]
	form.sala.choices=lista_salas
	if form.validate_on_submit():
		reserva.sala_id = form.sala.data
		reserva.observacoes = form.observacoes.data
		reserva.inicio = datetime.combine(form.data.data,form.hora_inicio.data)
		reserva.fim = datetime.combine(form.data.data,form.hora_fim.data)
		db.session.commit()
		flash('Reserva atualizada!', 'success')
		return redirect(url_for('reservas.reserva', reserva_id=reserva.id))
	elif request.method == 'GET':
		form.sala.data = Sala.query.get_or_404(reserva.sala_id)
		form.observacoes.data = reserva.observacoes
		form.data.data = reserva.inicio
		form.hora_inicio.data = reserva.inicio
		form.hora_fim.data = reserva.fim
	return render_template('criar_reserva.html', title='Atualizar reserva', form=form, legend="Atualizar reserva", primeira_sala=primeira_sala())

@reservas.route("/reservas/<int:reserva_id>/delete", methods=['GET', 'POST'])
@login_required
@verifica_permissao('excluir_reserva')
def delete_reserva(reserva_id):
	reserva = Reservas.query.get_or_404(reserva_id)
	if reserva.author != current_user:
		abort(403)
	db.session.delete(reserva)
	db.session.commit()
	flash('Reserva deletada!', 'success')
	return redirect(url_for('main.home'), primeira_sala=primeira_sala())

@reservas.route("/reservas/ver_reservas")
@login_required
@verifica_permissao('ver_reservas')
def ver_reservas():
	page = request.args.get('page', 1, type=int)
	#lista de reservas que estão válidas (salas reservadas para o momento atual ou posterior)
	# no momento em que o usuário está acessando o sistema
	reservas = Reservas.query.filter(Reservas.fim>=datetime.today()).order_by(Reservas.inicio).paginate(page=page, per_page=5)
	reservas_events = Reservas.query.filter(Reservas.fim>=datetime.today()).order_by(Reservas.inicio)
	salas = Sala.query.order_by(Sala.sala)
	return render_template('ver_reservas.html', reservas=reservas, salas=salas, events=reservas_events, primeira_sala=primeira_sala())

reservasalas/salas/routes.py
from datetime import datetime
from flask import (render_template, url_for, flash,
					redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from reservasalas import db
from reservasalas.models.models import Reservas, Sala
from reservasalas.salas.forms import SalaForm
from reservasalas.utils.utility_functions import primeira_sala
from reservasalas.utils.permissoes import verifica_permissao

from flask import Blueprint

salas = Blueprint('salas', __name__)

@salas.route("/sala/new", methods=['GET', 'POST'])
@login_required
@verifica_permissao('cadastrar_sala')
def nova_sala():
	form = SalaForm()
	if form.validate_on_submit():
		sala= Sala(sala=form.sala.data, tipo_sala=form.tipo_sala.data,
					 tipo_lousa=form.tipo_lousa.data, tipo_piso=form.tipo_piso.data,
					  capacidade=form.capacidade.data, andar=form.andar.data, campus=form.campus.data,
					   bloco_torre=form.bloco_torre.data, author=current_user)
		db.session.add(sala)
		db.session.commit()
		flash('Sala cadastrada!', 'success')
		return redirect(url_for('main.home'))
	salas_query = Sala.query.order_by(Sala.sala)
	primeira_sala_id_select = int(salas_query.first().id if salas_query!=None else -1)
	return render_template('criar_sala.html', title='Nova Sala', form = form, legend="Criar sala", primeira_sala=primeira_sala())

@salas.route("/sala/<int:sala_id>")
def sala(sala_id):
	reservas = Reservas.query.filter(Reservas.sala_id==sala_id and Reservas.fim>=datetime.today())
	reservas2=reservas.filter(Reservas.fim>=datetime.today())
	sala = Sala.query.get_or_404(sala_id)
	salas_query = Sala.query.order_by(Sala.sala)
	primeira_sala_id_select = int(salas_query.first().id if salas_query!=None else -1)
	return render_template('sala.html', sala=sala, reservas=reservas2,primeira_sala=primeira_sala())

@salas.route("/sala/<int:sala_id>/update", methods=['GET', 'POST'])
@login_required
@verifica_permissao('atualizar_sala')
def update_sala(sala_id):
	sala = Sala.query.get_or_404(sala_id)
	if sala.author != current_user:
		abort(403)
	form = SalaForm()
	if form.validate_on_submit():
		sala.sala = form.sala.data
		sala.tipo_sala = form.tipo_sala.data
		sala.tipo_lousa = form.tipo_lousa.data
		sala.tipo_piso = form.tipo_piso.data
		sala.capacidade = form.capacidade.data
		sala.andar = form.andar.data
		sala.campus = form.campus.data
		sala.bloco_torre = form.bloco_torre.data
		db.session.commit()
		flash('Sala atualizada!', 'success')
		return redirect(url_for('salas.sala', sala_id=sala.id))
	elif request.method == 'GET':
		form.sala.data = sala.sala
		form.tipo_sala.data = sala.tipo_sala
		form.tipo_lousa.data = sala.tipo_lousa
		form.tipo_piso.data = sala.tipo_piso
		form.capacidade.data = sala.capacidade
		form.andar.data = sala.andar
		form.campus.data = sala.campus
		form.bloco_torre.data = sala.bloco_torre
	return render_template('criar_sala.html', title='Atualizar sala', form=form, legend="Atualizar sala", primeira_sala=primeira_sala())

@salas.route("/sala/<int:sala_id>/delete", methods=['GET', 'POST'])
@login_required
@verifica_permissao('deletar_sala')
def delete_sala(sala_id):
	sala = Sala.query.get_or_404(sala_id)
	if sala.author != current_user:
		abort(403)
	db.session.delete(sala)
	db.session.commit()
	flash('Sala deletada!', 'success')
	return redirect(url_for('main.home'), primeira_sala=primeira_sala())

reservasalas/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from reservasalas import db#, bcrypt
from reservasalas.models.models import User, Sala
from reservasalas.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from reservasalas.utils.ldap import checa_ldap
#from reservasalas.users.utils import save_picture
from reservasalas.utils.utility_functions import primeira_sala

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		#hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') #criptografando a senha do usuário
		user = User(username=form.username.data, login=form.login.data)#, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your account has been created!', 'success')
		return redirect(url_for('main.home'))
	return render_template('register.html', title='Register', form=form, primeira_sala=primeira_sala())

@users.route("/login", methods=['GET','POST'])
def login():
	form = LoginForm()

	if current_user.is_authenticated:
		return redirect(url_for('main.home'))

	if form.validate_on_submit():
		login = form.login.data
		senha = form.password.data

		ok = login and senha and checa_ldap(login, senha)

		if not ok:
			flash("Usário ou senha errados! Tente novamente", 'danger')
			return render_template('login.html', title='Login', form=form)
		
		user=User.query.filter_by(login=form.login.data).first()
		if user is None:
			flash('Seu usuário não está cadastrado no sistema!', 'warning')
			return render_template('login.html', title='Login', form=form)
		
		login_user(user, remember=form.remember.data)
		next_page = request.args.get('next')
		return redirect(next_page) if next_page else redirect(url_for('main.home'))

		# user=User.query.filter_by(login=form.login.data).first()
		# if user and bcrypt.check_password_hash(user.password, form.password.data):
		# 	login_user(user, remember=form.remember.data)
		# 	next_page = request.args.get('next')
		# 	return redirect(next_page) if next_page else redirect(url_for('main.home'))
		# else:
		# 	flash('Login Unsuccessful.', 'danger')
	return render_template('login.html', title='Login', form=form, primeira_sala=primeira_sala())

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		#if form.picture.data:
		#	picture_file = save_picture(form.picture.data)
		#	current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.login = form.login.data
		db.session.commit()
		flash('Your account has been updated!', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET': #condição para pegar os dados do usuário e coloca-los nos inputs
		form.username.data = current_user.username
		form.login.data = current_user.login
	#image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html', title='Account', 
							#image_file = image_file,
							form = form, primeira_sala=primeira_sala())

#@users.route("/user/<string:username>")
#def user_posts(username):
#	page = request.args.get('page', 1, type=int) #parâmetro de consulta de páginas. Sem ele na próxima linha, apenas seria mostrada uma única página
#	user = User.query.filter_by(username=username).first_or_404()
#	posts = Post.query.filter_by(author=user)\
#		.order_by(Post.date_posted.desc())\
#		.paginate(page=page, per_page=2) #fazendo com que não sejam mostradas todas os posts de uma única vez. Nesse caso serão mostrados apenas 5 posts
#	return render_template('user_posts.html', posts = posts, user = user)

reservasalas/templates/calendar.html
{% block content %}
    <div id="calendar" style="flex-grow: 1;">
        <script>
            let calendarEl = document.getElementById('calendar');
            document.addEventListener('DOMContentLoaded', function() {
                var calendarEl = document.getElementById('calendar');
                let calendar = new FullCalendar.Calendar(calendarEl, {
                    events : [
                        {% for event in events %}
                            {
                                title : '{{ event.reservante }}',
                                start : '{{ event.inicio }}',
                                end: '{{ event.fim }}',
                                extendedProps: {
                                    sala_nome: '{{ event.sala_nome }}'
                                },
                                url: "{{ url_for('reservas.reserva', reserva_id=event.id) }}"
                            },
                        {% endfor %}
                ],
                eventDidMount: function(info) {
                    console.log(info.event.extendedProps);
                    $(info.el).tooltip({
                        title: "Sala: "+info.event.extendedProps.sala_nome+" Início: "+info.event.start.getHours()+"h"+info.event.start.getMinutes()+"min"+" - Fim: "+info.event.end.getHours()+"h"+info.event.end.getMinutes()+"min",
                        container: 'body',
                        delay: { "show": 50, "hide": 50 }
                    });
                }});
                calendar.render();
            });
        </script>
    </div>
{% endblock content %}

reservasalas/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	<!-- Calendar.JS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css">
	<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js"></script>

	<!-- CSS -->
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

	<!-- jquery -->
	<script src="https://code.jquery.com/jquery-3.6.1.js"></script>

	{% if title %}
		<title>Reserva de salas - {{title}}</title>
	{% else %}
		<title>Reserva de salas</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
  		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    		<div class="container">
      			<a class="navbar-brand mr-4" href="/">Reserva de salas</a>
      			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        			<span class="navbar-toggler-icon"></span>
      			</button>
      			<div class="collapse navbar-collapse" id="navbarToggle">
        			<div class="navbar-nav mr-auto">
          				<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
          				<a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
						<a class="nav-item nav-link" href="{{ url_for('reservas.ver_reservas') }}">Ver todas reservas</a>
        			</div>
        			<!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if current_user.is_authenticated %}
							<a class="nav-item nav-link" href="{{ url_for('salas.nova_sala') }}">Cadastrar sala</a>
							<a class="nav-item nav-link" href="{{ url_for('reservas.nova_reserva', sala_id=primeira_sala) }}">Reservar sala</a>
							<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
							<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						{% else %}
							<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
							<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
						{% endif %}
					</div>
					<!--<form method="POST" action="{{"""url_for('main.search')"""}}" class="d-flex">
						{{""" form.hidden_tag() """}}
						<input class="form-control me-2" type="search" placeholder="Procurar sala" aria-label="Search", name="searched">
						<button class="btn btn-outline-secondary" type="submit">Pesquisar</button>
					</form>-->
				</div>
			</div>
		</nav>
	</header>
	<main role="main" class="container">
		<div class="col-md-8">
			{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category, message in messages %}
						<div class="alert alert-{{ category }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
		{% block content %}{% endblock %}
		</div>
		<!--<div class="col-md-4">
		<div class="content-section">
			<h3>Our Sidebar</h3>
			<p class='text-muted'>You can put any information here you'd like.
			<ul class="list-group">
				<li class="list-group-item list-group-item-light">Latest Posts</li>
				<li class="list-group-item list-group-item-light">Announcements</li>
				<li class="list-group-item list-group-item-light">Calendars</li>
				<li class="list-group-item list-group-item-light">etc</li>
			</ul>
			</p>
		</div>-->
		<div class="calendar">
			{% include "calendar.html" %}
		</div>
	</main>
</body>
</html>

reservasalas/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				<div class="form-group">
					{{ form.login.label(class="form-control-label") }}
					{% if form.login.errors %}
						{{ form.login(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.login.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.login(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
            <small class="text-muted ml-2">
                <a href="#">Forgot password?</a>
            </small>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
{% endblock content %}

reservasalas/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.login.label(class="form-control-label") }}
					{% if form.login.errors %}
						{{ form.login(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.login.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.login(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			</p>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign in</a>
{% endblock content %}

reservasalas/templates/reserva.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h1 class="article-title">{{ sala.sala }}</h1>
                <!--<small class="text-muted">{{ reserva.inicio }}</small>-->
                {% if reserva.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('reservas.update_reserva', reserva_id=reserva.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <p class="article-content">Reservante: {{ reserva.reservante }}</p>
            <p class="article-content">Início: {{ reserva.inicio.strftime('%H:%M') }}</p>
            <p class="article-content">Fim: {{ reserva.fim.strftime('%H:%M') }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Deletar reserva em {{ sala.sala }}?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{ url_for('reservas.delete_reserva', reserva_id=reserva.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}